services:
  postgres:
    image: postgres:16-alpine
    container_name: dmf-postgres
    environment:
      POSTGRES_DB: documenten
      POSTGRES_USER: documenten
      POSTGRES_PASSWORD: documenten
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U documenten"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    container_name: dmf-keycloak
    image: keycloak/keycloak:latest
    command:
      - start-dev
      - --import-realm
      - -Dkeycloak.migration.strategy=SKIP
    environment:
      - KEYCLOAK_ADMIN=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
      - KC_DB_URL_HOST=postgres
      - KC_DB_PASSWORD=documenten
      - KC_DB=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=documenten
    ports:
      - "8081:8080"
    volumes:
      - ./data/realm-export.json:/opt/keycloak/data/import/realm.json
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build: .
    container_name: dmf-app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/documenten
      DB_USER: documenten
      DB_PASSWORD: documenten
      OIDC_ISSUER: http://localhost:8081/realms/cg-dmf
      ZGW_ALLOWED_CLIENT_IDS: gzac
    depends_on:
      postgres:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    container_name: dmf-minio
    # restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - CONSOLE_ACCESS_KEY=admin
      - CONSOLE_SECRET_KEY=admin
    command: server --address ":9000" --console-address ":9001" /data
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:

