{{- if and .Values.adminPortal.enabled (not .Values.adminPortal.settings.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cg-dmf.adminPortal.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cg-dmf.adminPortal.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ required "adminPortal.settings.nextauthSecret is required" .Values.adminPortal.settings.nextauthSecret | quote }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.adminPortal.settings.keycloakClientSecret | default "" | quote }}
{{- end }}

