{{- if not .Values.settings.database.existingSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cg-dmf.databaseSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cg-dmf.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  DB_URL: {{ .Values.settings.database.url | quote }}
  DB_USER: {{ .Values.settings.database.username | quote }}
  DB_PASSWORD: {{ required "settings.database.password is required" .Values.settings.database.password | quote }}

---

{{- end }}

{{- if not .Values.settings.blobStorage.existingSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cg-dmf.blobStorageSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cg-dmf.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  BLOB_STORAGE_ACCESS_KEY1: {{ required "settings.blobStorage.accessKey is required" .Values.settings.blobStorage.accessKey | quote }}
  BLOB_STORAGE_SECRET_KEY1: {{ required "settings.blobStorage.secretKey is required" .Values.settings.blobStorage.secretKey | quote }}

---

{{- end }}

{{- if not .Values.settings.openzaak.existingSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cg-dmf.openzaakSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cg-dmf.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  OPENZAAK_CLIENT_SECRET: {{ required "settings.openzaak.clientSecret is required" .Values.settings.openzaak.clientSecret | quote }}

{{- end }}
