ALTER TABLE eio_versions ADD formaat VARCHAR(255) DEFAULT '' NULL;
ALTER TABLE eio_versions ADD bestandsomvang BIGINT NULL;
ALTER TABLE eio_versions ADD link VARCHAR(200) DEFAULT '' NOT NULL;
ALTER TABLE eio_versions ADD integriteit_algoritme VARCHAR(20) DEFAULT '' NOT NULL;
ALTER TABLE eio_versions ADD integriteit_waarde VARCHAR(128) DEFAULT '' NOT NULL;
ALTER TABLE eio_versions ADD integriteits_datum TIMESTAMP NULL;
ALTER TABLE eio_versions ADD begin_registratie TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE eio_versions ADD verschijnings_vorm TEXT DEFAULT '' NOT NULL;
ALTER TABLE eio_versions ADD trefwoorden VARCHAR(100)[] DEFAULT ARRAY[]::varchar[] NOT NULL;
ALTER TABLE eio_versions ADD "locked" BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE eio_versions ADD bron_organisatie VARCHAR(9) DEFAULT '' NOT NULL;
ALTER TABLE eio_versions ADD creatie_datum DATE DEFAULT CURRENT_DATE NOT NULL;
ALTER TABLE eio_versions ADD titel VARCHAR(200) NOT NULL;
ALTER TABLE eio_versions ADD vertrouwlijkheids_aanduiding VARCHAR(20) DEFAULT '' NOT NULL;
ALTER TABLE eio_versions ADD auteur VARCHAR(200) NOT NULL;
ALTER TABLE eio_versions ADD status VARCHAR(20) DEFAULT '' NOT NULL;
ALTER TABLE eio_versions ADD beschrijving TEXT DEFAULT '' NOT NULL;
ALTER TABLE eio_versions ADD indicatie_gebruiksrecht BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE eio_versions ADD ondertekening_soort VARCHAR(10) DEFAULT '' NOT NULL;
ALTER TABLE eio_versions ADD ondertekenings_datum TIMESTAMP NULL;
ALTER TABLE eio_versions ALTER COLUMN taal TYPE VARCHAR(3), ALTER COLUMN taal SET NOT NULL;
