apiVersion: v2
name: cg-dmf
description: >
  Document Management Facility (DMF) – a Proof-of-Concept implementation of the
  Common Ground Documenten API (DRC) written in Kotlin.
type: application
version: 0.9.9
appVersion: "0.9.9"
keywords:
  - common-ground
  - documenten-api
  - drc
  - kotlin
home: https://github.com/baseflow/cg-dmf-poc
sources:
  - https://github.com/baseflow/cg-dmf-poc
maintainers:
  - name: Baseflow

