# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2026 Gemeente Utrecht
name: 'Test run for pull requests'
run-name: "Building '${{ github.ref_name}}' by '${{ github.actor }}'"

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    permissions:
      issues: write
    uses: ./.github/workflows/LINT.yml

  test:
    uses: ./.github/workflows/TEST.yml
    secrets: inherit
